site_name: Intelligent Loan Underwriting (ILOUL)
site_description: AI Agent Capabilities for Financial Services Workflows
repo_url: https://github.com/rrbanda/iloul
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Use Case Overview: 01-use-case-overview.md
  - Comprehensive Process: 02-business-process-full.md
  - Simplified Process: 03-business-process-simplified.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - content.code.copy
    - content.code.annotate
    - navigation.top

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details

extra_javascript:
  - https://unpkg.com/mermaid@10.6.0/dist/mermaid.min.js

extra_css:
  - https://unpkg.com/mermaid@10.6.0/dist/mermaid.min.css
