apiVersion: apps/v1
kind: Deployment
metadata:
  name: mortgage-business-rules-mcp
  namespace: rh12026
  labels:
    app: mortgage-business-rules-mcp
    component: mcp-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mortgage-business-rules-mcp
  template:
    metadata:
      labels:
        app: mortgage-business-rules-mcp
        component: mcp-server
    spec:
      containers:
      - name: mcp-server
        image: mortgage-business-rules-mcp:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NEO4J_URI
          value: "bolt://mortgage-db-0.mortgage-db-headless:7687"
        - name: NEO4J_USERNAME
          value: "neo4j"
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mortgage-db-secret
              key: password
        - name: NEO4J_DATABASE
          value: "mortgage"
        - name: NEO4J_TRANSPORT
          value: "http"
        - name: NEO4J_MCP_SERVER_HOST
          value: "0.0.0.0"
        - name: NEO4J_MCP_SERVER_PORT
          value: "8080"
        - name: NEO4J_MCP_SERVER_PATH
          value: "/mcp/"
        - name: NEO4J_READ_ONLY
          value: "true"
        - name: NEO4J_MCP_SERVER_ALLOWED_HOSTS
          value: "*"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /mcp/
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /mcp/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: mortgage-business-rules-mcp-service
  namespace: rh12026
  labels:
    app: mortgage-business-rules-mcp
spec:
  selector:
    app: mortgage-business-rules-mcp
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mortgage-business-rules-mcp-route
  namespace: rh12026
  labels:
    app: mortgage-business-rules-mcp
spec:
  to:
    kind: Service
    name: mortgage-business-rules-mcp-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
