apiVersion: apps/v1
kind: Deployment
metadata:
  name: mortgage-agents
  labels:
    app: mortgage-agents
    component: api-server
    version: v1.0.0
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: mortgage-agents
      component: api-server
  template:
    metadata:
      labels:
        app: mortgage-agents
        component: api-server
        version: v1.0.0
    spec:
      # OpenShift Security Context Constraints (SCC) Configuration
      securityContext:
        # Use restricted SCC - compatible with OpenShift default security policies
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 0
        fsGroup: 0
        seccompProfile:
          type: RuntimeDefault
      
      containers:
      - name: mortgage-agents
        image: quay.io/rbrhssa/mortgage-agents:latest
        imagePullPolicy: IfNotPresent
        
        # Container security context
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 0
          readOnlyRootFilesystem: false  # Set to true after testing
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        
        ports:
        - containerPort: 2024
          name: http
          protocol: TCP
        
        # Environment variables from ConfigMap and Secret
        env:
        - name: PYTHONPATH
          value: "/opt/app-root/src/mortgage-agents"
        - name: CONFIG_FILE
          value: "/opt/app-root/src/mortgage-agents/config/config.yaml"
        
        # Environment variables from Secret
        envFrom:
        - secretRef:
            name: mortgage-agents-secrets
        
        # Resource limits and requests
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        
        # Volume mounts for configuration and data
        volumeMounts:
        - name: config-volume
          mountPath: /opt/app-root/src/mortgage-agents/config
          readOnly: true
        - name: data-volume
          mountPath: /opt/app-root/src/mortgage-agents/data
        - name: logs-volume
          mountPath: /opt/app-root/src/mortgage-agents/logs
        - name: tmp-volume
          mountPath: /tmp
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        
        # Startup probe for initial container startup
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30
      
      # Volumes
      volumes:
      - name: config-volume
        configMap:
          name: mortgage-agents-config
          defaultMode: 0644
      - name: data-volume
        persistentVolumeClaim:
          claimName: mortgage-agents-data-pvc
      - name: logs-volume
        emptyDir:
          sizeLimit: 1Gi
      - name: tmp-volume
        emptyDir:
          sizeLimit: 100Mi
      
      # Pod scheduling and affinity
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: mortgage-agents
              topologyKey: kubernetes.io/hostname
      
      # Tolerations for specific node taints (if needed)
      tolerations:
      - key: "mortgage-workload"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      
      # Service account for RBAC
      serviceAccountName: mortgage-agents-sa
      
      # DNS configuration
      dnsPolicy: ClusterFirst
      
      # Restart policy
      restartPolicy: Always
      
      # Termination grace period
      terminationGracePeriodSeconds: 30

---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mortgage-agents-hpa
  labels:
    app: mortgage-agents
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mortgage-agents
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
