apiVersion: v1
kind: Secret
metadata:
  name: mortgage-agents-secrets
  labels:
    app: mortgage-agents
    component: secrets
type: Opaque
stringData:
  # LLM Configuration - Replace with actual values
  LLM_BASE_URL: "https://lss-lss.apps.prod.rhoai.rh-aiservices-bu.com/v1/openai/v1"
  LLM_API_KEY: "not-needed"
  LLM_DEFAULT_MODEL: "llama-4-scout-17b-16e-w4a16"
  
  # Neo4j Configuration - Replace with actual production values
  NEO4J_URI: "bolt://neo4j-service:7687"
  NEO4J_USERNAME: "neo4j"
  NEO4J_PASSWORD: "REPLACE-WITH-PRODUCTION-PASSWORD"
  NEO4J_DATABASE: "mortgage"
  
  # Database Configuration - Replace with actual production values
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"
  DB_NAME: "mortgage_db"
  DB_USERNAME: "mortgage_user"
  DB_PASSWORD: "REPLACE-WITH-PRODUCTION-PASSWORD"

---
# Sealed Secret Template (for GitOps workflows)
# To create a sealed secret:
# 1. Replace the values above with actual production credentials
# 2. Create the secret: kubectl create secret generic mortgage-agents-secrets --from-file=.env --dry-run=client -o yaml > secret-raw.yaml
# 3. Seal the secret: kubeseal -f secret-raw.yaml -w sealed-secret.yaml
# 4. Delete the raw secret file and commit only the sealed secret
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mortgage-agents-sealed-secrets
  namespace: mortgage-agents
spec:
  # This will be populated when you seal the actual secret
  # encryptedData:
  #   LLM_API_KEY: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAx...
  #   NEO4J_PASSWORD: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAx...
  template:
    metadata:
      name: mortgage-agents-secrets
      namespace: mortgage-agents
    type: Opaque
